### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by davypaulino** [Meia-noite-eu-te-conto/Transcendence#3]
- [x] retirar botões sem uso
- [x] bug de varios players na hora do game
- [x] ajustar erro do single player
- [x] ajustar o history game
- [x] adicionar o "you" no player
- [x] verificar o tamanho dos torneios e ajustar se for menor do que 16
- [x] redirecionamento toda vez que alguem se connectar no ws daquela partida
- [x] verificar os input de usuário contra sql injection
- [ ] verificar back and forward buttons
- [x] não prioritario (verificar o lang)
- [x] limpar arquivos sem uso
- [ ] tirar o .env 
- [x] ajustar o docker compose 
- [x] rodar em um VM o projeto

https://tcdmodules.vercel.app/v14.1?state=19663047
